### Get publisher
GET localhost:8080/publishers/get?id=1

### Create publisher
POST localhost:8080/publishers/create
Content-Type: application/x-www-form-urlencoded

name=Publisher25

### Update publisher
POST localhost:8080/publishers/update
Content-Type: application/x-www-form-urlencoded

id=1&name=Publisher2

### Delete publisher
POST localhost:8080/publishers/delete
Content-Type: application/x-www-form-urlencoded

id=5